# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-12 12:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190211_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='title',
            field=models.CharField(max_length=50, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='emailverfyrecord',
            name='send_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='发送时间'),
        ),
        migrations.AlterField(
            model_name='emailverfyrecord',
            name='send_tpye',
            field=models.CharField(choices=[('Register', '注册'), ('Forget', '忘记密码')], max_length=20, verbose_name='发送类型'),
        ),
    ]
